---
resources:
  - name: git-dev
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: feature/794/gatling-in-concourse

  - name: slack
    type: slack-alert
    source:
      url: ((slack_hook_automate))
      channel: covid-engineering-team

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-dev
        trigger: true
      - set_pipeline: svp-form
        file: git-dev/concourse_dev/pipeline.yml

  - name: test
    serial: true
    plan:
      - get: git-dev
        trigger: true
        passed: [update-pipeline]
      - task: test
        file: git-dev/concourse/tasks/test.yml
