version: '3'
services:
  chrome-driver:
    image: gdscyber/concourse-chrome-driver:latest
    network_mode: host
    volumes:
      - ./behave:/usr/src/app
    command: bash
    environment:
      - WEB_APP_BASE_URL=http://localhost:5000
    ports:
      - "8081:8081"
  rds-client-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      RESOURCE_ARN: 'arn:aws:rds:eu-west-2:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:eu-west-2:123456789012:secret:dummy'
    ports:
      - "8080:80"
