---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.3-ibmjava-8-alpine
inputs:
  - name: git-dev
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    # User journey is 16 requests long, and we want close to 1000 req/s, so inject 1000/16 users/s here, with a pause of
    # 1 second between requests.
    # Run simulation for 30 mins to ensure workflow execution time is covered.
    # Suppress html file output (doesn't seem possible to completely remove file output...)
    # Suppress console log to final report only (done by turning off console writer)
    - |
      cd loadtests
      mvn clean gatling:test \
        -DinjectUsersPerSecond=63 \
        -DinjectDurationSeconds=1800 \
        -DpauseBetweenRequestsInSeconds=1 \
        -DnumberOfRepetitions=1 \
        -Dgatling.simulationClass=svp.SvpSimulationConstantUsersPerSec \
        -Dgatling.data.charting.noReports=true \
        -Dgatling.data.writers.0=file
  dir: git-dev
