---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.3-ibmjava-8-alpine
inputs:
  - name: git-dev
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      cd loadtests
      mvn clean gatling:test
  dir: git-dev
