---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.8.5-slim-buster
params:
  DEBIAN_FRONTEND: "noninteractive"
inputs:
- name: git-master
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      root=$(pwd)
      echo "Installing dependencies..."
      pip3 install -r requirements-dev.txt
      echo "Executing unit tests..."
      python3 -m pytest -sqx --disable-warnings
  dir: git-master
