---
resource_types:
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource
      username: ((docker_hub_username))
      password: ((docker_hub_password))

  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource
      username: ((docker_hub_username))
      password: ((docker_hub_password))

resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: 994-Glue-failures

  - name: slack
    type: slack-alert
    source:
      url: ((slack_hook_automate))
      channel: covid-engineering-team

  - name: trigger-at-1am
    type: cron-resource
    source:
      expression: "0 1 * * *"
      location: "Local"

# Anchors for later
slack_alert_on_failure: &slack_alert_on_failure
  put: slack
  params:
    alert_type: failed

slack_alert_on_success: &slack_alert_on_success
  put: slack
  params:
    alert_type: success

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: svp-form-temp-gatling
        file: git-master/concourse/pipeline.yml
    on_failure: *slack_alert_on_failure

  - name: run-daily-and-mi-workflows-in-staging
    plan:
      - get: git-master
      - get: trigger-at-1am
        trigger: true
      - task: get-aws-credentials
        file: git-master/concourse/tasks/get-gatling-tester-aws-creds.yml
        params:
          ACCOUNT_ID: 375282846305
          ENVIRONMENT: staging
          REGION: eu-west-2
          DURATION: 21600
      - task: run-pipelines
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: git-master
            - name: aws-credentials
          params:
            ENVIRONMENT: "staging"
            REGION: "eu-west-2"
            SALT: "1rjoBuOtDYaid83fYRJBFU5ouUi0nSueev2BhyoEhnw"
          run:
            path: bash
            args:
              - -c
              - |
                set -euo pipefail
                echo "Installing system dependencies:"
                apt-get update
                apt-get upgrade -y
                apt-get install -y jq curl unzip git make python3 python3-pip
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                ./aws/install

                echo "Installing libraries required for test:"
                source ../aws-credentials/.env
                make install
                echo "Running Python script:"
                python3 scripts/trigger_glue_workflow_and_check_outcome.py
            dir: git-master
