---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-develop
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: concourse-pipelines

  - name: govuk-coronavirus-services-tech-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/((slack_webhook_url))

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-develop
        trigger: true
      - set_pipeline: shielded-vulnerable-people-form
        file: git-develop/concourse/pipeline.yml

  - name: deploy-to-dev
    serial: true
    plan:
      - get: git-develop
        trigger: true
        passed: [update-pipeline]
#        passed: [run-quality-checks]
      - task: deploy-to-paas
        config:
        file: git-develop/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: dev
          INSTANCES: 1
          WORKER_INSTANCES: 1
          CF_STARTUP_TIMEOUT: 5 # minutes
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
          SECRET_KEY_BASE: ((secret-key-base-dev))
          HOSTNAME: ((gds-shielded-vulnerable-people-service-dev))
          GOVUK_NOTIFY_EMAIL_TEMPLATE_ID: d4fddfce-1dfd-4ff5-ab42-156e6ba3e76b
          GOVUK_NOTIFY_SMS_TEMPLATE_ID: a2166a39-91f5-4370-bbbf-c59276975d49
          NOTIFY_API_KEY: ((notify-api-key-test))
        on_failure:
          put: govuk-coronavirus-services-tech-slack
          params:
            channel: '#covid-engineering-team'
            username: 'Concourse (Shielded Vulnerable Service)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Deploy to staging for the Shielded Vulnerable service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
