platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/curl-ssl
    username: ((docker_hub_username))
    password: ((docker_hub_password))
run:
  path: sh
  args:
    - -c
    - |
      set -ue
      echo "Curling cronitor ${CRONITOR_ENDPOINT}..."
      curl --fail "${CRONITOR_URL}${CRONITOR_ENDPOINT}"
      echo 'Curled cronitor successfully.'
