platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest
inputs:
  - name: git-master
  - name: aws-credentials
params:
  ENVIRONMENT: "staging"
  REGION: "eu-west-2"
  SALT: "1rjoBuOtDYaid83fYRJBFU5ouUi0nSueev2BhyoEhnw"
  POSTCODE_TIER_OVERRIDE:
run:
  path: bash
  args:
    - -c
    - |
      set -euo pipefail
      echo "Installing system dependencies:"
      apt-get update
      apt-get upgrade -y
      apt-get install -y jq curl unzip git make python3 python3-pip
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install

      echo "Installing libraries required for test:"
      source ../aws-credentials/.env
      make install
      echo "Running Behave test case:"
      make concourse_e2e_with_pipeline_validation_s3_check
  dir: git-master
